### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by AlexAndrei98** [sicpa-dlab/didcomm-react-native#65]
After doing an npm install and adding the boilerplate code to the App file I get the following error:
```
TypeError: null is not an object (evaluating 'DIDCommResolversProxyModule.getConstants')
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:95:17 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:141:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:39 in handleError
at node_modules/expo/build/errors/ExpoErrorManager.js:25:19 in errorHandler
at node_modules/expo/build/errors/ExpoErrorManager.js:30:24 in <anonymous>
at node_modules/@react-native/polyfills/error-guard.js:49:36 in ErrorUtils.reportFatalError
at node_modules/metro-runtime/src/polyfills/require.js:203:40 in guardedLoadModule
at http://192.168.1.71:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:null in global code
```
It looks like it is complaining that DIDCommResolversProxyModule is not getting found

**Comment by dmitry-vychikov** [comment]
@AlexAndrei98 

Did you try steps mentioned here? https://docs.expo.dev/workflow/using-libraries/#installing-a-third-party-library

Like
```
npx expo install @sicpa_open_source/didcomm-react-native
```

**Comment by AlexAndrei98** [comment]
@dmitry-vychikov I gave it a try but now I am having issues with `⠦ Couldn't install: didcomm-react-native » DidcommSDK. Updating the Pods project and trying again...` which I saw that someone opened an issue [here](https://github.com/sicpa-dlab/didcomm-react-native/issues/44) but seems like that they passed forward.
